// Landing-page palette and type constants. "LP" = Landing Page.
export const LP = {
  // Warm espresso darks + cream lights — the golden-hour cabin palette.
  carbon: '#1B1511',
  surface: '#261E17',
  ivory: '#F5EEE1',
  bone: '#EDE5D5',
  inkOnIvory: '#241C14',
  mutedOnIvory: '#6E6455',
  textOnDark: '#EDE5D5',
  mutedOnDark: '#9C9083',
  emerald: '#20C878',
  emeraldDeep: '#0E8A4E',
  gold: '#B58A3A',
  borderDark: 'rgba(237,229,213,0.12)',
  borderLight: 'rgba(36,28,20,0.14)',
  skyTop: '#9DBBD6',
  skyBottom: '#7E9FBE',
  skyMid: '#8FB0CC',
  textOnSky: '#FAFCFE',
  display: "'Archivo', 'Sora', 'Inter', sans-serif",
  displayHero: "'Unbounded', 'Archivo', 'Sora', sans-serif",
  champagne: '#D6B77A',
  mono: "'JetBrains Mono', monospace",
} as const;
